const Routes = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  HOME: "/",
  ROLES: "/roles",
  PERMISOS: "/permisos",
  USUARIOS: "/usuarios",
  CARGA_BD: "/cargarBase",
  RETIRAR_BD: "/retirarBase",
  ASIGNAR_BD: "/asignarBaseNew",
  HABILITAR_INHABILITAR: "/habilitar-deshabilitar",
  BITACORA_CLIENTES: "/bitacora-clientes",
  BITACORA_CREDITO: "/bitacora-credito",
  BITACORA_PDP: "/bitacora-pdp",
  TRAMA_GESTION: "/gestionTrama",
  INDICADORES: "/indicadores",
  BREAK_TIMES: "/breaktimes",
  BD_GESTIONADA: "/baseGestionada",
  MARKING_AGENTS: "/marcacion-agentes",
  INICIO_GESTION: "/inicio-gestion",
  DESHABILITAR_BD: "/deshabilitarBase",
  GESTIONAR: "/gestion",
};
export default Routes;
